### ISSUE TITLE
No longer working - "Request subdomain does not match account subdomain"

### ISSUE THREAD

**Issue by kaoru** [emq/workable#15]
Hey,

This gem seems to have stopped working due to changes on Workable's end. It was working fine with the following code:

```
class WorkableProvider
  attr_reader :client

  WORKABLE_ACCESS_TOKEN = ENV['WORKABLE_ACCESS_TOKEN'] || raise('missing WORKABLE_ACCESS_TOKEN')
  WORKABLE_SUBDOMAIN = ENV['WORKABLE_SUBDOMAIN'] || raise('missing WORKABLE_SUBDOMAIN')

  def initialize
    @client = Workable::Client.new(api_key: WORKABLE_ACCESS_TOKEN, subdomain: WORKABLE_SUBDOMAIN)
  end

  def jobs_as_json
    jobs.to_json(only: ['url', 'title'])
  end

  def jobs
    @jobs ||= client.jobs(state: 'published').data
  end
end
```

But now we are getting the error "Request subdomain does not match account subdomain".

I think it's because the gem builds the base API URL according to some out-dated rules.

https://github.com/emq/workable/blob/15b1410e97dd25ef28f6a0938f21efbb168f0ad2/lib/workable/client.rb#L240-L243

I've got it working for us now by patching the `#api_url` method like so:

```
# Patch Workable::Client class's #api_url method for new version of the API
module Workable
  class Client
    def api_url
      'https://%s.workable.com/spi/v%s/jobs' % [subdomain, Workable::API_VERSION]
    end
  end
end
```

**Comment by rwojsznis** [comment]
Hi @kaoru ! Thanks for reporting this; I do not longer use workable on daily basis, but will definitely try to take a look! Weirdly enough workable's API is still versioned as v3, but it seems their subdomain rule changes in a breaking way indeed 🤔 

update: welp, seems in order to access their real API you are now need to buy a paid plan 🙈 will see if workable provide official ruby gem by chance so maybe I can deprecate mine - if not I will try to contact them

**Comment by kaoru** [comment]
Yeah it's super weird that they didn't change the version but did change the URL structure 😅 

We do have a paid plan with them, but I'm afraid I can't volunteer to take over maintenance of the gem since we only use a single end-point 😛 I have no idea what the rest of the API can do haha.

Even stranger still... their API seems to have started working with the old URLs again!

```
$ curl -s -H "Content-Type: application/json" -H "Authorization:Bearer XXX" 'https://charliehr.workable.com/spi/v3/jobs?state=published' | jq '.jobs[0].title'
"Senior Software Developer - Ruby"

$ curl -s  -H "Content-Type: application/json" -H "Authorization:Bearer XXX" 'https://www.workable.com/spi/v3/accounts/charliehr/jobs?state=published' | jq '.jobs[0].title'
"Senior Software Developer - Ruby"
```

I swear that wasn't working yesterday 😂 Maybe someone else complained to them? Or did you do it?

**Comment by rwojsznis** [comment]
That's interesting, thanks for taking your time and reporting back! 🙇 

> Or did you do it?

I did not yet; I 'reached out' by requesting API access on my newly registered account yesterday (no response just yet) - as otherwise, it would be rather hard to verify what needs fixing 🙈 .

I will try to follow up on that tho within next week as it seems there is no other ruby client alternative when it comes to workable. So it would be great to keep this gem alive for the rest of the open-source community.

**Comment by kaoru** [comment]
I think when they broke it it was a bug and they've since fixed it 🤷‍♂ The old-style and new-style URLs are both working again now. I'm going to close this issue, but be prepared to re-open it if they break it again haha 😄
